(()=>{const D=window.FITS_DATA;if(!D)return;const addPiece=p=>{if(!D.pieces.some(x=>x.id===p.id))D.pieces.push(p)};const addFamily=f=>{if(!D.families.some(x=>x.id===f.id))D.families.push(f)};const addLook=l=>{if(!D.looks.some(x=>x.id===l.id))D.looks.push(l)};
addPiece({id:'olive-overshirt',name:'Olive overshirt',category:'Outerwear',status:'missing'});
addPiece({id:'black-polo',name:'Black polo',category:'Top',status:'missing'});
addPiece({id:'cream-knit-sweater',name:'Cream knit sweater',category:'Top',status:'missing'});
addFamily({id:'family-olive-overshirt-denim',name:'Olive overshirt + denim',hero:'look-51',looks:['look-51']});
addLook({id:'look-51',family:'family-olive-overshirt-denim',name:'Olive overshirt + white tee + dark denim + white sneakers',image:'assets/look-51-olive-overshirt-denim.webp?v=1',formal:1,badges:['Weekend','Travel'],pieces:['olive-overshirt','white-tee','dark-denim','white-leather-sneakers']});
addFamily({id:'family-black-polo-denim',name:'Black polo + denim',hero:'look-52',looks:['look-52']});
addLook({id:'look-52',family:'family-black-polo-denim',name:'Black polo + dark denim + white sneakers',image:'assets/look-52-black-polo-denim.webp?v=1',formal:1,badges:['Weekend','Dinner','Travel'],pieces:['black-polo','dark-denim','white-leather-sneakers']});
const look40=D.looks.find(x=>x.id==='look-40');if(look40)look40.image='assets/look-40-navy-polo-cream-v2.webp?v=1';
addFamily({id:'family-lightblue-cream-knit',name:'Light blue shirt + cream trousers',hero:'look-53',looks:['look-53']});
addLook({id:'look-53',family:'family-lightblue-cream-knit',name:'Light blue shirt + cream knit + cream trousers + brown loafers',image:'assets/look-53-lightblue-cream-cafe.webp?v=1',formal:3,badges:['Office','Dinner','Weekend'],pieces:['light-blue-oxford','cream-knit-sweater','cream-chinos','brown-loafers','brown-belt']});
})();