const DATA=window.FITS_DATA, CATALOG=window.FITS_CATALOG_IMAGES||{};
function safe(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch(e){return fallback}}
const q=new URLSearchParams(location.search),piece=id=>DATA.pieces.find(p=>p.id===id),look=id=>DATA.looks.find(l=>l.id===id),family=id=>DATA.families.find(f=>f.id===id);
const fam=family(q.get('family'))||DATA.families[0],looks=fam.looks.map(look).filter(Boolean);let active=look(q.get('look'))||look(fam.hero)||looks[0];
let wardrobe=safe('fitsWardrobe',{}),wear=safe('fitsWearHistory',{}),saved=safe('fitsSavedVariants',{});
DATA.pieces.forEach(p=>{if(!wardrobe[p.id])wardrobe[p.id]=p.status==='owned'?'owned':'missing';if(wardrobe[p.id]!=='owned')wardrobe[p.id]='missing'});localStorage.setItem('fitsWardrobe',JSON.stringify(wardrobe));
function isOwned(id){return wardrobe[id]==='owned'}
function icon(c){if(c===0)return'☀️';if(c<=2)return'🌤️';if(c===3)return'☁️';if(c===45||c===48)return'🌫️';if((c>=51&&c<=67)||(c>=80&&c<=82))return'🌧️';if(c>=71&&c<=86)return'❄️';if(c>=95)return'⛈️';return'☁️'}
function currentWeather(){const w=safe('fitsWeatherHome',null);return w&&Date.now()-w.ts<3600000?w:null}
function fit(w){if(!w)return{level:'neutral',label:'Weather pending',reason:'Enable weather on Looks for live suggestions.'};const names=active.pieces.map(id=>(piece(id)?.name||'').toLowerCase()).join(' '),t=Math.round(w.temp),rain=w.currentRain||w.maxRain>=40,outer=/blazer|jacket|vest|coat|sweater|cardigan/.test(names),dress=/loafer|derbies|dress shoe/.test(names),sneakers=/sneaker/.test(names);if(t>=25&&outer)return{level:'caution',label:'Might feel warm',reason:'The extra layer may feel heavy.'};if(t<=12&&!outer)return{level:'caution',label:'Could feel cool',reason:'Consider a light layer.'};if(rain&&dress&&!sneakers)return{level:'caution',label:'Weather note',reason:'Rain may make dress shoes less practical.'};if(t>=22&&!outer)return{level:'good',label:'Great today',reason:'Lighter pieces suit the temperature.'};if(rain&&sneakers)return{level:'good',label:'Good today',reason:'Sneakers are easier if rain shows up.'};return{level:'neutral',label:'Could work',reason:'Weather should not be a major issue.'}}
function hourLabel(iso){return new Date(iso).toLocaleTimeString([], {hour:'numeric'}).replace(' ','').toLowerCase()}
function weatherHTML(w){if(!w)return`<div class="weather"><div class="weather-note">Weather unavailable · enable location on Looks for live suggestions.</div></div>`;let hs=(w.hours||[]).slice(0,4);if(!hs.length)hs=[{time:new Date().toISOString(),temp:w.temp,rain:w.maxRain||0,code:w.code||2}];return`<div class="weather"><div class="weather-row">${hs.map((h,i)=>`<div class="wx"><div class="t">${i===0?'Now':hourLabel(h.time)}</div><div class="ico">${icon(h.code||2)}</div><div class="deg">${Math.round(h.temp)}°</div></div>`).join('')}</div><div class="weather-note">${fit(w).reason}</div></div>`}
function shortName(){return fam.name.replace(' chinos','').replace(' polo','')}
function diff(v){if(v.id===looks[0].id)return'Base look';const base=looks[0],add=v.pieces.filter(x=>!base.pieces.includes(x)).map(x=>piece(x)?.name).filter(Boolean),rem=base.pieces.filter(x=>!v.pieces.includes(x)).map(x=>piece(x)?.name).filter(Boolean);if(add.length===1&&rem.length===1)return`${rem[0]} → ${add[0]}`;if(add.length===1)return`Add ${add[0]}`;return v.name}
function count(){return(wear[active.id]||[]).length}function last(){const h=wear[active.id]||[];return h.length?new Date(h[h.length-1]+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):'Never'}
window.wearToday=function(){const d=new Date().toISOString().slice(0,10),history=wear[active.id]||[],i=history.indexOf(d);if(i>=0)history.splice(i,1);else history.push(d);wear[active.id]=history.sort();localStorage.setItem('fitsWearHistory',JSON.stringify(wear));render()};window.toggleSaved=function(){saved[active.id]=!saved[active.id];localStorage.setItem('fitsSavedVariants',JSON.stringify(saved));render()};window.findItem=function(id){const p=piece(id);if(!p)return;window.open(`https://www.google.com/search?udm=28&q=${encodeURIComponent(p.name+" men's clothing Canada")}`,'_blank','noopener,noreferrer')};
function render(){const w=currentWeather(),f=fit(w),today=new Date().toISOString().slice(0,10),worn=(wear[active.id]||[]).includes(today);document.getElementById('root').innerHTML=`<div class="app"><header class="top"><div class="toprow"><a class="iconbtn" href="index.html">‹</a><div class="title">${shortName()}</div><button class="iconbtn bookmark" onclick="toggleSaved()">${saved[active.id]?'★':'☆'}</button></div>${weatherHTML(w)}</header><main><div class="hero"><img src="${active.image}" alt="${active.name}"></div><div class="statusrow"><span class="status ${f.level}">${f.label}</span>${active.badges.map(x=>`<span class="status">${x}</span>`).join('')}</div><div class="actions"><button class="btn primary" onclick="wearToday()">${worn?'✓ Worn today':'I’ll wear this'}</button><button class="btn ${saved[active.id]?'saved':''}" onclick="toggleSaved()">${saved[active.id]?'Saved ✓':'Save variant'}</button></div>${looks.length>1?`<section class="section"><div class="sectionhead"><h2>Variants</h2><span>${looks.length} real combinations</span></div><div class="variants">${looks.map(v=>`<a class="variant ${v.id===active.id?'active':''}" href="detail.html?family=${fam.id}&look=${v.id}"><div class="variant-media"><img src="${v.image}" alt="${v.name}"></div><div class="vname">${v.name}</div><div class="vdiff">${diff(v)}</div></a>`).join('')}</div></section>`:''}<section class="section"><div class="sectionhead"><h2>Items in this look</h2><span>${active.pieces.length} pieces</span></div><div class="pieces">${active.pieces.map(id=>{const p=piece(id),own=isOwned(id),img=CATALOG[id];return`<article class="piece">${img?`<div class="piece-photo"><img src="${img}" alt="${p.name}" loading="lazy"></div>`:`<div class="piece-photo"></div>`}<span class="own-pill ${own?'':'no'}">${own?'OWNED':'NEED'}</span><strong>${p.name}</strong><small>${p.category}</small>${!own?`<button class="find-btn" onclick="findItem('${id}')">⌕ Find item to buy ↗</button>`:''}</article>`}).join('')}</div></section><section class="section"><div class="sectionhead"><h2>Rotation</h2><span>this exact variant</span></div><div class="wearmeta"><div class="meta"><b>${count()}×</b><span>Worn</span></div><div class="meta"><b>${last()}</b><span>Last worn</span></div></div></section></main><nav class="nav"><a class="active" href="index.html"><b>▦</b>Looks</a><a href="wardrobe.html"><b>◇</b>Wardrobe</a><a href="unlock.html"><b>↗</b>Unlock</a></nav></div>`}
render();
