const DATA=window.FITS_DATA;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function safe(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch(e){return fallback}}
function piece(id){return DATA.pieces.find(p=>p.id===id)}
function look(id){return DATA.looks.find(l=>l.id===id)}
function familyLooks(f){return f.looks.map(look).filter(Boolean)}
function ownedMap(){const raw=safe('fitsWardrobe',{}),m={};DATA.pieces.forEach(p=>m[p.id]=(raw[p.id]==='owned'||(!raw[p.id]&&p.status==='owned'))?'owned':'missing');return m}
function readyCount(f){const own=ownedMap();return familyLooks(f).filter(l=>l.pieces.every(id=>own[id]==='owned')).length}
function shortName(f){return ({'family-green-khaki':'Green + khaki','family-burgundy-charcoal':'Burgundy + charcoal','family-white-navy':'White + navy','family-navy-grey':'Navy + grey','family-navy-taupe':'Navy + taupe','family-charcoal-navy':'Charcoal + navy','family-charcoal-lightgrey':'Charcoal + light grey','family-navy-denim':'Navy + denim'})[f.id]||f.name}
function icon(c){if(c===0)return'☀️';if(c<=2)return'🌤️';if(c===3)return'☁️';if(c===45||c===48)return'🌫️';if((c>=51&&c<=67)||(c>=80&&c<=82))return'🌧️';if(c>=71&&c<=86)return'❄️';if(c>=95)return'⛈️';return'☁️'}
function weatherLabel(c){if(c===0)return'Clear';if(c<=2)return'Partly cloudy';if(c===3)return'Cloudy';if(c===45||c===48)return'Foggy';if((c>=51&&c<=67)||(c>=80&&c<=82))return'Rain';if(c>=71&&c<=86)return'Snow';if(c>=95)return'Storm';return'Cloudy'}
function heroFit(f,w){if(!w)return{level:'neutral',label:'Weather pending',reason:'Weather should not be a major issue.'};const h=look(f.hero)||familyLooks(f)[0],names=h.pieces.map(id=>(piece(id)?.name||'').toLowerCase()).join(' '),t=Math.round(w.temp),rain=w.currentRain||w.maxRain>=40,outer=/blazer|jacket|vest|coat|sweater|cardigan/.test(names),dress=/loafer|derbies|dress shoe/.test(names),sneakers=/sneaker/.test(names);if(t>=25&&outer)return{level:'caution',label:'Might feel warm',reason:'The extra layer may feel heavy later.'};if(t<=12&&!outer)return{level:'caution',label:'Could feel cool',reason:'You may want an extra layer.'};if(rain&&dress&&!sneakers)return{level:'caution',label:'Weather note',reason:'Rain makes the dressier shoes less practical.'};if(t>=22&&!outer)return{level:'good',label:'Great today',reason:'Lighter pieces suit the temperature.'};if(rain&&sneakers)return{level:'good',label:'Good today',reason:'Sneakers are easier if rain shows up.'};return{level:'neutral',label:'Could work',reason:'Weather should not be a major issue.'}}
function hourLabel(iso){return new Date(iso).toLocaleTimeString([], {hour:'numeric'}).replace(' ','').toLowerCase()}
function weatherHTML(w){if(!w)return `<section class="weather"><div class="weather-head"><div><div class="location">TODAY</div><div class="now"><div class="temp">—°</div><div class="condition"><strong>Weather-aware fits</strong><span>Now + later today</span></div></div></div><button class="weather-btn" id="weatherBtn">Use location</button></div><div class="weather-advice">Weather changes suggestions, never hides an outfit.</div></section>`;const hours=(w.hours||[]).slice(0,6);return `<section class="weather"><div class="weather-head"><div><div class="location">TODAY · ${(w.location||'YOUR LOCATION').toUpperCase()}</div><div class="now"><div class="temp">${Math.round(w.temp)}°</div><div class="condition"><strong>${weatherLabel(w.code)}</strong><span>${w.maxRain>=40?'Rain possible later':'Low rain risk'}</span></div></div></div><button class="weather-btn" id="weatherBtn">Refresh</button></div><div class="weather-advice">${w.maxRain>=40?'Rain may affect shoes or layers later today.':'Conditions look pretty flexible for most outfits.'}</div>${hours.length?`<div class="timeline-wrap"><div class="timeline-label">Now → later</div><div class="timeline">${hours.map((h,i)=>`<div class="hour ${i===0?'active':''}"><div class="time">${i===0?'Now':hourLabel(h.time)}</div><div class="icon">${icon(h.code)}</div><div class="deg">${Math.round(h.temp)}°</div><div class="rain">${Math.round(h.rain)}% rain</div></div>`).join('')}</div></div>`:''}</section>`}
function cardHTML(f,w){const vs=familyLooks(f),h=look(f.hero)||vs[0],fit=heroFit(f,w),badges=[...new Set(vs.flatMap(v=>v.badges))],ready=readyCount(f),second=vs.find(v=>v.id!==h.id);return `<a class="card" data-tags="${badges.join(',')}" href="detail.html?family=${f.id}"><div class="visual"><img class="look-img" src="${h.image}" alt="${h.name}">${second?`<img class="variant-thumb" src="${second.image}" alt="${second.name}"><span class="variant-count">${vs.length} variants</span>`:''}<span class="tag ${fit.level}">${fit.label}</span></div><div class="body"><h3>${shortName(f)}</h3><p>${fit.reason}</p><div class="badges">${badges.map(x=>`<span class="badge">${x}</span>`).join('')}</div></div></a>`}
function render(w){const root=$('#root'),readyFamilies=DATA.families.filter(f=>readyCount(f)>0).length,counts={good:0,neutral:0,caution:0};DATA.families.forEach(f=>counts[heroFit(f,w).level]++);root.innerHTML=`<div class="app"><header class="top"><div class="brandrow"><div class="brand">Fits</div><div class="count">${DATA.families.length} families</div></div><div class="sub">Same style. A smarter rotation.</div></header><main>${weatherHTML(w)}<div class="summary"><div class="sum"><b>${w?counts.good:'—'}</b><span>Great today</span></div><div class="sum"><b>${w?counts.neutral:'—'}</b><span>Could work</span></div><div class="sum"><b>${w?counts.caution:'—'}</b><span>Weather note</span></div></div><div class="chips">${['All','Office','Weekend','Dinner','Travel'].map((x,i)=>`<button class="chip ${i===0?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="grid">${DATA.families.map(f=>cardHTML(f,w)).join('')}<div class="empty">No families in this filter yet.</div></div><div class="build">Fits build 1.0 · ${DATA.looks.length} real variants · ${readyFamilies} wearable families</div></main><nav class="nav"><a class="active" href="index.html"><b>▦</b>Looks</a><a href="wardrobe.html"><b>◇</b>Wardrobe</a><a href="unlock.html"><b>↗</b>Unlock</a></nav></div>`;wire();}
function wire(){$$('.chip').forEach(btn=>btn.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;let visible=0;$$('.card').forEach(c=>{const show=f==='All'||c.dataset.tags.split(',').includes(f);c.classList.toggle('hidden',!show);if(show)visible++});$('.empty').style.display=visible?'none':'block'});const wb=$('#weatherBtn');if(wb)wb.onclick=loadWeather;}
async function resolveLocation(lat,lon){try{const r=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${lat}&longitude=${lon}&localityLanguage=en`),d=await r.json();return d.locality||d.city||d.principalSubdivision||'Your location'}catch(e){return'Your location'}}
function loadWeather(){const b=$('#weatherBtn');if(b){b.textContent='Loading…';b.disabled=true}if(!navigator.geolocation){if(b){b.textContent='Unavailable';b.disabled=false}return}navigator.geolocation.getCurrentPosition(async pos=>{try{const{latitude,longitude}=pos.coords,start=new Date();const [r,location]=await Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,precipitation,rain,weather_code&hourly=temperature_2m,precipitation_probability,weather_code&forecast_days=1&temperature_unit=celsius&timezone=auto`),resolveLocation(latitude,longitude)]),d=await r.json(),c=d.current,idx=d.hourly.time.findIndex(t=>new Date(t)>=start),hours=[];for(let i=Math.max(idx,0);i<Math.min((idx<0?0:idx)+6,d.hourly.time.length);i++)hours.push({time:d.hourly.time[i],temp:d.hourly.temperature_2m[i],rain:d.hourly.precipitation_probability[i]||0,code:d.hourly.weather_code[i]});const maxRain=Math.max(0,...hours.map(h=>h.rain)),w={temp:c.temperature_2m,code:c.weather_code,currentRain:(c.rain||c.precipitation)>0,maxRain,hours,location,ts:Date.now()};localStorage.setItem('fitsWeatherHome',JSON.stringify(w));localStorage.setItem('fitsWeather',JSON.stringify({t:w.temp,rainy:w.currentRain||w.maxRain>=40,location:w.location,ts:w.ts}));render(w)}catch(e){render(null)}},()=>render(null),{enableHighAccuracy:false,timeout:10000,maximumAge:3600000})}
const cached=safe('fitsWeatherHome',null);render(cached&&Date.now()-cached.ts<3600000?cached:null);