(()=>{
  const D=window.FITS_DATA;if(!D)return;let season='All';
  const owned=id=>typeof isOwned==='function'?isOwned(id):false;
  const missing=l=>(l.pieces||[]).filter(id=>!owned(id));
  const eligible=l=>season==='All'||(l.seasons||[]).includes(season);
  function impactFor(p){let used=0,completes=0,nearReady=0,distance=0;const families=new Set(),completedFamilies=new Set(),nearFamilies=new Set();D.looks.filter(eligible).forEach(l=>{if(!(l.pieces||[]).includes(p.id))return;const m=missing(l);if(!m.includes(p.id))return;used++;families.add(l.family);distance+=1/Math.max(1,m.length);if(m.length===1){completes++;completedFamilies.add(l.family)}else if(m.length===2){nearReady++;nearFamilies.add(l.family)}});const familyReach=families.size,score=(completedFamilies.size*1200)+(completes*500)+(nearFamilies.size*220)+(nearReady*90)+(familyReach*45)+(distance*35)+(used*4);return{...p,used,completes,nearReady,familyReach,completedFamilies:completedFamilies.size,nearFamilies:nearFamilies.size,distance,score}}
  function reason(p){if(p.completes>0)return{tier:'ready',label:p.completes===1?'UNLOCK NOW':`UNLOCK ${p.completes} LOOKS`,headline:`Completes ${p.completes} wearable look${p.completes===1?'':'s'} now`,support:p.completedFamilies===1?'Finishes 1 style family immediately.':`Finishes ${p.completedFamilies} style families immediately.`};if(p.nearReady>0)return{tier:'near',label:'HIGH IMPACT',headline:`Gets ${p.nearReady} look${p.nearReady===1?'':'s'} to one piece away`,support:`Useful across ${p.familyReach} style famil${p.familyReach===1?'y':'ies'} · ${p.used} real variant${p.used===1?'':'s'}.`};if(p.familyReach>1)return{tier:'reach',label:'VERSATILE',headline:`Helps ${p.familyReach} style families`,support:`Appears in ${p.used} real variant${p.used===1?'':'s'} across your saved looks.`};return{tier:'base',label:'LOWER PRIORITY',headline:'Helps 1 style family',support:`Appears in ${p.used} real variant${p.used===1?'':'s'} and does not complete one yet.`}}
  window.setUnlockSeason=function(s){season=s;renderUnlock()};
  window.renderUnlock=function(){const items=D.pieces.filter(p=>!owned(p.id)).map(impactFor).filter(x=>x.used).sort((a,b)=>b.score-a.score||b.familyReach-a.familyReach||b.used-a.used||a.name.localeCompare(b.name));const immediate=items.filter(x=>x.completes>0).length,highImpact=items.filter(x=>!x.completes&&x.nearReady>0).length,scope=season==='All'?'all seasons':season.toLowerCase();document.body.innerHTML=`<div class="app wardrobe-v2">${headerBar('Unlock','Buy fewer pieces. Unlock more outfits. Ranked from your actual wardrobe and saved looks.','smart buys')}<main><div class="unlock-season"><div class="unlock-season-head"><span>Shopping focus</span><b>${scope}</b></div><div class="unlock-season-chips">${['All','Summer','Transitional','Cold'].map(s=>`<button class="unlock-season-chip ${s===season?'active':''}" onclick="setUnlockSeason('${s}')">${s==='All'?'All seasons':s}</button>`).join('')}</div></div><div class="unlock-summary"><div><b>${immediate}</b><span>can unlock a look now</span></div><div><b>${highImpact}</b><span>high-impact next buys</span></div><div><b>${items.length}</b><span>missing pieces ranked</span></div></div><div class="notice">Ranking is calculated only from <b>${scope}</b> looks. Complete outfits win first, then pieces that move several real combinations closer to wearable.</div><div class="unlock-list-v2">${items.length?items.map((p,i)=>{const r=reason(p);return`<article class="unlock-card-v2 ${r.tier}"><div class="unlock-photo">${piecePhoto(p)}<span class="unlock-rank">${i+1}</span></div><div class="unlock-copy-v2"><div class="unlock-title-row"><strong>${p.name}</strong><span class="impact-pill ${r.tier}">${r.label}</span></div><span>${r.headline}</span><small>${r.support}</small><button class="find-item" onclick="searchItem('${p.id}')">⌕ Find item to buy <span>↗</span></button></div></article>`}).join(''):`<div class="unlock-empty">Nothing missing for ${scope}. Nice problem to have.</div>`}</div></main>${nav('unlock')}</div>`};
})();