(()=>{
  if(document.body.dataset.page!=='wardrobe')return;
  let category='All',ownership='All',query='';
  const CATEGORIES=['All','Shirts','T-Shirts & Polos','Sweaters','Pants','Shoes','Outerwear','Accessories'];
  function text(card){return((card.querySelector('.ward-card-copy strong')?.textContent||'')+' '+(card.querySelector('.ward-card-copy small')?.textContent||'')).toLowerCase()}
  function kind(card){const t=text(card);if(/belt|watch|accessor|tie|scarf|wallet/.test(t))return'Accessories';if(/shoe|sneaker|loafer|boot|chelsea|derb|brogue|wingtip|footwear/.test(t))return'Shoes';if(/blazer|jacket|coat|outerwear|bomber/.test(t))return'Outerwear';if(/sweater|crewneck|crew-neck|v-neck|quarter-zip|quarter zip|cardigan|turtleneck|knit/.test(t))return'Sweaters';if(/shirt|button-down|button down|button-up|button up|oxford|gingham|check/.test(t)&&!/t-shirt|tee|polo|henley/.test(t))return'Shirts';if(/t-shirt|tee|polo|henley/.test(t))return'T-Shirts & Polos';if(/trouser|chino|pant|denim|jean|bottom/.test(t))return'Pants';return'Other'}
  function normalized(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
  function apply(){const cards=[...document.querySelectorAll('.ward-card')],needle=normalized(query);let shown=0;cards.forEach(card=>{const categoryMatch=category==='All'||kind(card)===category;const ownershipMatch=ownership==='All'||(ownership==='Owned'&&card.classList.contains('is-owned'))||(ownership==='Missing'&&card.classList.contains('is-missing'));const searchMatch=!needle||normalized(text(card)).includes(needle);const show=categoryMatch&&ownershipMatch&&searchMatch;card.style.display=show?'':'none';if(show)shown++});document.querySelectorAll('.ward-section').forEach(section=>{section.style.display=[...section.querySelectorAll('.ward-card')].some(card=>card.style.display!=='none')?'':'none'});const count=document.querySelector('.wardrobe-filter-count');if(count)count.textContent=`${shown} ${shown===1?'item':'items'}`;const empty=document.querySelector('.wardrobe-search-empty');if(empty)empty.hidden=shown!==0}
  function chip(label,type){const active=(type==='category'?category:ownership)===label;return`<button class="wardrobe-filter-chip ${active?'active':''}" data-${type}="${label}">${label}</button>`}
  function enhance(){const grid=document.querySelector('.ward-grid');if(!grid)return;let bar=document.querySelector('.wardrobe-filterbar');if(!bar){bar=document.createElement('div');bar.className='wardrobe-filterbar';bar.innerHTML=`<label class="wardrobe-search"><span aria-hidden="true">⌕</span><input type="search" placeholder="Search by item, color or type" aria-label="Search wardrobe"><button type="button" aria-label="Clear search" hidden>×</button></label><div class="wardrobe-filter-head"><span>Category</span><b class="wardrobe-filter-count"></b></div><div class="wardrobe-filter-chips wardrobe-category-chips">${CATEGORIES.map(x=>chip(x,'category')).join('')}</div><div class="wardrobe-filter-head wardrobe-status-head"><span>Status</span></div><div class="wardrobe-filter-chips wardrobe-status-chips">${['All','Owned','Missing'].map(x=>chip(x,'ownership')).join('')}</div><div class="wardrobe-search-empty" hidden>No items match this search.</div>`;grid.before(bar);const input=bar.querySelector('input'),clear=bar.querySelector('.wardrobe-search button');input.addEventListener('input',()=>{query=input.value;clear.hidden=!query;apply()});clear.addEventListener('click',()=>{query='';input.value='';clear.hidden=true;input.focus();apply()});bar.querySelectorAll('[data-category]').forEach(btn=>btn.onclick=()=>{category=btn.dataset.category;bar.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x.dataset.category===category));apply()});bar.querySelectorAll('[data-ownership]').forEach(btn=>btn.onclick=()=>{ownership=btn.dataset.ownership;bar.querySelectorAll('[data-ownership]').forEach(x=>x.classList.toggle('active',x.dataset.ownership===ownership));apply()})}apply()}
  new MutationObserver(()=>requestAnimationFrame(enhance)).observe(document.body,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',()=>requestAnimationFrame(enhance));
})();
